package weka;

public enum StatNames
{
	PTS_FOR, PTS_AGAINST, FG_PERCENT, FT_PERCENT, THREE_PERCENT, EFF_PERCENT, PPWS,
	TO_RATE, BLOCKS, FOULS, OFF_REBS, TOT_REBS, STEALS, ASSISTS, POSS, OFF_PPP, DEF_PP

}
